### ISSUE TITLE
Switch PERP -> PARA for 11618 and 11620

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#37]
Hi Sean,

These 2 runs in the second priority group are labeled PERP in RCDB, but have the PARA phi modulation and are labeled PARA in the logbook.

11618: https://halldweb.jlab.org/rcdb/runs/info/11618
11620: https://halldweb.jlab.org/rcdb/runs/info/11620

Can you change them to PARA?

-Justin

**Comment by sdobbs** [comment]
Done

**Comment by jrstevenjlab** [comment]
Thanks Sean.  I looked again on the rcdb webpage and it still shows PERP for 11618 and 11620.  Is there some lag time in updating the DB before the page is updated?

**Comment by sdobbs** [comment]
Hm, not sure why there was a problem, but the DB should be fixed now.

**Comment by jrstevenjlab** [comment]
Thanks!
